server:
  port:
    8080

spring:
  application:
    name:
      gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: '*'
    circuitBreaker:
      resilience4j:
        enabled:
          true

jwt:
  secret: AvHGRK8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadweheufHNyG

logging:
  level:
    root:
      WARN
  file:
    max-size:
      10MB
    max-history:
      10
